### PR TITLE
Integrate TinyDB

### PR DESCRIPTION
**Pull request by Youngestdev**
# Goal

The TinyDB database is used to add persistence and enable the API to track changes made to the policy stored as a JSON file.

## Commits and changes

- [Persistent database for policies](https://github.com/r-scheele/rego_builder/pull/5/commits/a60cc31ca4bcb4ef18848c57673c40ec6858130c)
- [Route updates](https://github.com/r-scheele/rego_builder/pull/5/commits/f6fd5b1d01ba362a751df08976c5b3eab3af4011)
---

## Workings.

1. Create a policy

A policy is created by sending a request to the API:

```console
$ curl -X 'POST' \
  'http://127.0.0.1:8000/policy/save' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "auth",
  "rules": [
    [
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "request_path",
          "value": [
            "v1",
            "collections",
            "*"
          ]
        }
      },
      {
        "command": "input_prop_in",
        "properties": {
          "input_property": "company",
          "datasource_name": "items",
          "datasource_loop_variable": "name"
        }
      },
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "request_method",
          "value": "GET"
        }
      }
    ],
    [
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "request_path",
          "value": [
            "v1",
            "collections"
          ]
        }
      },
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "request_path",
          "value": [
            "v1",
            "collections",
            "lakes"
          ]
        }
      }
    ],
    [
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "request_path",
          "value": [
            "v1",
            "collections",
            "*"
          ]
        }
      },
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "company",
          "value": "geobeyond"
        }
      },
      {
        "command": "input_prop_in_as",
        "properties": {
          "datasource_name": "items",
          "datasource_loop_variables": [
            "name",
            "everyone"
          ],
          "input_properties": [
            "preferred_username",
            "groupname"
          ]
        }
      }
    ]
  ]
}'
```

The request above creates a policy stored in the database and then published to the [repository](https://github.com/Youngestdev/experiments/commit/1986cdcdd038604a7cd0cb0e1c364b4594dac21e).

2. Update policy

The fields to be changed are updated to update a policy, and another request is sent to the UPDATE route. The rego file is updated and then published to the GitHub repository. See:

```console
$ curl -X 'PUT' \
  'http://127.0.0.1:8000/policy/auth' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "rules": [
    [
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "request_path",
          "value": [
            "v1",
            "collections",
            "*"
          ]
        }
      },
      {
        "command": "input_prop_in",
        "properties": {
          "input_property": "company",
          "datasource_name": "items",
          "datasource_loop_variable": "name"
        }
      },
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "request_method",
          "value": "GET"
        }
      }
    ],
    [
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "request_path",
          "value": [
            "v1",
            "collections"
          ]
        }
      },
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "request_path",
          "value": [
            "v1",
            "collections",
            "lakes"
          ]
        }
      }
    ],
    [
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "request_path",
          "value": [
            "v1",
            "collections",
            "*"
          ]
        }
      },
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "company",
          "value": "fastgeoapi"
        }
      }
    ]
  ]
}'
```

A successful response is returned to confirm the operation status:

```JSON
{
  "status": 200,
  "message": "Updated successfully"
}
```

The repo has been updated as well - [Updated file](https://github.com/Youngestdev/experiments/commit/8219b6fd9045b2356686372d0f8734a7088e9fca)

3. Retrieve policy

To retrieve a policy, a request is sent to the `/policy/{name_of_ploicy}` route:

```console
$ curl -X 'GET' \
  'http://127.0.0.1:8000/policy/auth' \
  -H 'accept: application/json'
```

If the policy exists, it is returned otherwise, `null` is returned:

```JSON
{
  "name": "auth",
  "rules": [
    [
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "request_path",
          "value": [
            "v1",
            "collections",
            "*"
          ]
        }
      },
      {
        "command": "input_prop_in",
        "properties": {
          "input_property": "company",
          "datasource_name": "items",
          "datasource_loop_variable": "name"
        }
      },
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "request_method",
          "value": "GET"
        }
      }
    ],
    [
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "request_path",
          "value": [
            "v1",
            "collections"
          ]
        }
      },
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "request_path",
          "value": [
            "v1",
            "collections",
            "lakes"
          ]
        }
      }
    ],
    [
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "request_path",
          "value": [
            "v1",
            "collections",
            "*"
          ]
        }
      },
      {
        "command": "input_prop_equals",
        "properties": {
          "input_property": "company",
          "value": "fastgeoapi"
        }
      }
    ]
  ]
}
```

4. Delete a policy

A request is sent to `/policy/{name}`:

```console
$ curl -X 'DELETE' \
  'http://127.0.0.1:8000/policy/auth' \
  -H 'accept: application/json'
```

A successful response returns the state of the request:

```JSON
{
  "status": 200,
  "message": "Policy deleted successfully."
}
```
---
## Todo

- Update the `DELETE` route to remove the policy from the repository.

### CODE REVIEW

**Comment by francbartoli** [comment]
I see this has been already merged but it looks like the tinydb dependency is not declared in the poetry configuration file

**Comment by Youngestdev** [comment]
> I see this has been already merged but it looks like the tinydb dependency is not declared in the poetry configuration file

I'll add that. Thanks for pointing that out, @francbartoli

**Comment by r-scheele** [comment]
> I see this has been already merged but it looks like the tinydb dependency is not declared in the poetry configuration file

We don't have individual branches yet [We'll have this as soon as possible], it was merged to ensure the code is working as expected. I'll review and update as required

**Comment by r-scheele** [comment]
@Youngestdev please make the update, so I can pull.

**Comment by Youngestdev** [comment]
> > I see this has been already merged but it looks like the tinydb dependency is not declared in the poetry configuration file
> 
> We don't have individual branches yet [We'll have this as soon as possible], it was merged to ensure the code is working as expected. I'll review and update as required

Hm. This is wrong, I make updates from a different individual branch. 

You can ( should ) review PRs before merging 😇. 

I’ll update the dependency after fixing the Todo listed in the PR body.

**Pull request merged**
